apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: certbot-letsencrypt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
