apiVersion: v1
kind: Pod
metadata:
  labels:
    app: certbot-ocp
    name: certbot-ocp
  name: certbot-ocp
spec:
  containers:
  - env:
    - name: EMAIL
      value: your_email@here.com
    - name: CERTBOT_EXTRA_OPTS
      value: "--test"
    image: quay.io/fevermap/certbot-ocp:latest
    imagePullPolicy: IfNotPresent
    name: certbot-ocp
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: 
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi 
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/letsencrypt
      name: letsencrypt
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  serviceAccount: certbot-ocp-sa
  serviceAccountName: certbot-ocp-sa
  terminationGracePeriodSeconds: 10
  volumes:
  - name: letsencrypt
    persistentVolumeClaim:
      claimName: certbot-letsencrypt